stages:
  - integration-test

cache:
  key:
    files:
      - package.json
      - package-lock.json
  paths:
    - node_modules

before_script:
  - npm install

integration-test:
  stage: integration-test
  only:
    - branches
  image: node:lts-gallium
  variables:
    DOCKER_HOST: "tcp://localhost:2375"
    DOCKER_TLS_CERTDIR: ""
  tags:
    - dind
  services:
    - docker:19.03.5-dind
  script:
    - npm run build
    - npm run test
    - npm run example:redis
    - npm run example:redis-typescript
